# Relative Abundance Analysis

## Library

```{r, eval = F}
library("phyloseq"); packageVersion("phyloseq")
library("ggplot2"); packageVersion("ggplot2")

```
## Load the dataset

```{r, eval= F}
load("/Users/matiasbeckerburgos/Desktop/Master_in_Bioinformatics/Master_Thesis/Hawaiian_feral_Chicken_Microbiome/Backup_workspace/Decomtamination_pipeline.RData")
```

## Set Theme

```{r, eval = F}
theme_set(theme_bw())
```

## Top Phyla check

```{r, eval = F}
barplot_phylum <- psmelt(ps_Norm)
table(barplot_phylum$Phylum, useNA="ifany") # table of phyla
barplot_phylum$Phylum[barplot_phylum$Phylum==""] <- "NA" # change if there are empty names to NA
table(barplot_phylum$Phylum, useNA="ifany") # check

# calculate sum of abundances
taxa_summary <- aggregate(barplot_phylum$Abundance, by=list(Category= barplot_phylum$Phylum), FUN=sum)
taxa_summary <- taxa_summary[order(-taxa_summary$x) ,]
taxa_summary
```

Print off top 5 Phyla

```{r, eval = F}
list(as.character(taxa_summary[c(1:5),1]))

top_phyla <- as.character(c("Bacillota","Bacteroidota","Pseudomonadota","Actinomycetota","Verrucomicrobiota"))

# Function
'%!in%' <- function(x,y)!('%in%'(x,y))

# For-loop and if then function that checks to see if any of the names in the list "top" is in the 
# barplot_phylum$Phylum column, leaves unchanged if it is, changes it to "Other" if it isn't
# Re-name all uncommon phyla as "Other"
for (i in seq_along(barplot_phylum$Phylum)) {
  if (barplot_phylum$Phylum[i] %!in% top_phyla) {
    barplot_phylum$Phylum[i] <- "Other"
  }
}

# Re-name NA:s as "Other"
barplot_phylum$Phylum[is.na(barplot_phylum$Phylum)] <- "Other"
```

Change order so "Other" is last, change the rest to whichever order you prefer:

```{r, eval = F}
barplot_phylum$Phylum <- factor(barplot_phylum$Phylum, levels= c("Bacillota","Bacteroidota","Pseudomonadota","Actinomycetota","Verrucomicrobiota", "Other"))
levels(barplot_phylum$Phylum)
```

## Relative Abundance by samples

```{r, eval = F}
ggplot(barplot_phylum, aes(x = Sample, y=Abundance, order = Phylum)) + 
  geom_bar((aes(fill=Phylum)), stat="identity", position="stack", width = 1) +
  ylab("Relative abundance") + xlab("Sample") + theme_bw() #+
  # coord_flip() + # comment out this line if you want vertical bars
  #theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
  #theme(axis.title.x = element_text(size=13), 
        axis.title.y = element_text(size=13),
        axis.text.y = element_text(size=12, color ="black"), 
        axis.text.x = element_text(size=6)) +
  #theme(legend.title = element_text(size=14), 
        legend.text = element_text(size=12),
        legend.key.size=unit(0.7,"cm") ) +
  #theme(axis.text.x = element_text(angle = 90)) +
  #scale_fill_manual(values=(color_list[c(10,6,8,5,4,3)])) + 
  #facet_grid(~Sample_type, scales="free", space="free") + # change this per your liking!
  #scale_y_continuous(expand = c(0,0)) +
  #theme(strip.text.x = element_text(size = 8, color = "black"), 
        #strip.background = element_rect(fill = "#ffffff"))
```

```{r, eval = F}
# Not normalized
plot_bar(ps)
# Normalized data
plot_bar(ps_Norm)
```

```{r, eval = F}
# Not normalized
plot_bar(ps, fill = "Phylum") + geom_bar(aes(color=Phylum, fill=Phylum), stat="identity", position="stack") #+ theme(legend.position = "none")
# Normalized data
plot_bar(ps_Norm, fill = "Phylum") + geom_bar(aes(color=Phylum, fill=Phylum), stat="identity", position="stack") #+ theme(legend.position = "none")
```

## Relative Abundance by island

```{r, eval = F}
# species abundance between island
plot_bar(ps_Norm, x = "island", fill = "species")

# species level between island and samples
plot_bar(ps_Norm, "samples", fill = "species", facet_grid = ~island)
```

## Relative Abundance by sex

```{r, eval = F}
# Abundance between sex
plot_bar(ps_Norm, x = "Sex", fill = "species")

# Abundance between sex and island
plot_bar(ps_Norm, "Sex", fill = "species", facet_grid = ~island)
```

## Relative Abundance by community

```{r}
# Look how to do it but maybe nice idea


```


